### ISSUE TITLE
Music Suddenly Stop 

### ISSUE THREAD

**Issue by MrConqueror** [mostafaalagamy/Metrolist#1]
![Screenshot_2023-09-03-08-49-47-392_com metrolist music](https://github.com/mostafaalagamy/Metrolist/assets/102837820/f929bd4b-4466-4e0e-bf5f-8eced8dadb65)
I Played a song to listen and Click on a Start Radio. While i was doing something the music Suddenly Stop i don't know why so i get up and fetch my phone. it's just stop not pause as you can see the button is ⏸️

**Comment by mostafaalagamy** [comment]
This is a problem with RAM usage in Xiaomi devices.

**Comment by mostafaalagamy** [comment]
> 

This is a problem with RAM usage in Xiaomi devices.
