### ISSUE TITLE
Fix and bring back Lrclib lyrics

### ISSUE THREAD

**Issue by SiddhantRakh** [mostafaalagamy/Metrolist#11]
I know that Metrolist, as of the latest beta version, uses Kuguo as the primary synchronized lyrics provider, but Lrclib is superior in almost every aspect.
Lrclib has lyrics for most of the Hindi songs I listen to, while Kuguo does not. Even Kuguo lacks lyrics for most unpopular English songs, which Lrclib provides.

**Comment by mostafaalagamy** [comment]
> I know that Metrolist, as of the latest beta version, uses Kuguo as the primary synchronized lyrics provider, but Lrclib is superior in almost every aspect.
> Lrclib has lyrics for most of the Hindi songs I listen to, while Kuguo does not. Even Kuguo lacks lyrics for most unpopular English songs, which Lrclib provides.

All these fixes I am doing from my phone, and this takes a long time and is extremely difficult. Despite this, I am trying to fix the matter until I get my PC , and the shape of the three points has also been changed as requested.

**Comment by SiddhantRakh** [comment]
> > I know that Metrolist, as of the latest beta version, uses Kuguo as the primary synchronized lyrics provider, but Lrclib is superior in almost every aspect.
> > Lrclib has lyrics for most of the Hindi songs I listen to, while Kuguo does not. Even Kuguo lacks lyrics for most unpopular English songs, which Lrclib provides.
> 
> All these fixes I am doing from my phone, and this takes a long time and is extremely difficult. Despite this, I am trying to fix the matter until I get my PC , and the shape of the three points has also been changed as requested.

Please take your time to fix it. I might have sounded a bit hasty. I don't know how hard it can be, but I totally respect and appreciate the time and effort you are putting into this.

**Comment by SiddhantRakh** [comment]
Hey Malopeids recently added a commit about the lyrics issue. Maybe you can merge it with Metrolist, and this issue will be solved. 
It would also be great if you could make a beta release too.

**Comment by mostafaalagamy** [comment]
> Hey Malopeids recently added a commit about the lyrics issue. Maybe you can merge it with Metrolist, and this issue will be solved. It would also be great if you could make a beta release too.

It can be tested now

**Comment by SiddhantRakh** [comment]
> > Hey Malopeids recently added a commit about the lyrics issue. Maybe you can merge it with Metrolist, and this issue will be solved. It would also be great if you could make a beta release too.
> 
> It can be tested now

Thanks. You made my day.
