### ISSUE TITLE
Songs Not Playing - Unknown Error

### ISSUE THREAD

**Issue by anxiouslelimo** [mostafaalagamy/Metrolist#113]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Some songs doesn't play in random

### Expected behavior

Songs should play

### Actual behavior

song doesn't play

### Screenshots/Screen recordings

![Screenshot_20241109-101303](https://github.com/user-attachments/assets/ff1f1975-3764-4e10-8898-cf485d998cdd)

### Logs

Nil

### Metrolist version

10.0.0-fix

### Android version

14

### Additional information

unplayable song play after the app is closed and reopened.

**Comment by mostafaalagamy** [comment]
I'll look into this , I think I've found the issue.

**Comment by mostafaalagamy** [comment]
issue has been resolved now, check the release build in latest commit.

**Comment by ghost** [comment]
Thank you for prompt bug fix. Error not encountered. Could you push an update.?

**Comment by mostafaalagamy** [comment]
> Thank you for prompt bug fix. Error not encountered. Could you push an update.?

I think the update will be tomorrow

**Comment by mostafaalagamy** [comment]
can you try the latest release or debug version and let me know if the issue still exists?

**Comment by ghost** [comment]
Tried the latest release version. No error.

**Comment by ImpenetrableNoble** [comment]
@mostafaalagamy I'm having the same issue for a single album that I wanted to play apparently.

![Screenshot_20241127_053402](https://github.com/user-attachments/assets/937fa88b-7bb7-4e51-8159-c4e6ff2cfc3a)
![Screenshot_20241127_053341](https://github.com/user-attachments/assets/998c903b-ea4f-4320-a970-11497fc2e643)

**Comment by mostafaalagamy** [comment]
Hello all,

"Try the latest stable or debug version, but log out for it to work, until I finish identifying and fixing the issue."
