### ISSUE TITLE
Playback functionality Issue 

### ISSUE THREAD

**Issue by ImpenetrableNoble** [mostafaalagamy/Metrolist#120]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to discord. 
2. Turn on rich presence. 
3. Tap profile. 

### Expected behavior

Improve UI performance. 

### Actual behavior

Playback time for zero minutes and zero seconds stays at the start point of the song I played on discord. 

### Screenshots/Screen recordings

![Screenshot_20241112_224846](https://github.com/user-attachments/assets/7a561a18-a958-4417-9599-c5bd07179224)

### Logs

N/A

### Metrolist version

10.1.0

### Android version

Android 12

### Additional information

I hope this can be fixed.

**Comment by mostafaalagamy** [comment]
good catch, resolved now.
