### ISSUE TITLE
No Stream available ???

### ISSUE THREAD

**Issue by Spaceshiprace** [mostafaalagamy/Metrolist#13]
bug

**Comment by mostafaalagamy** [comment]
> bug
> 
> https://github.com/mostafaalagamy/Metrolist/assets/156727749/47c391c9-65d9-4b55-9d93-8d5e58eed944
> 
> 

Works normally with me! 

![Screenshot_2024-05-17-18-09-39-629_com.metrolist.music.jpg](https://github.com/mostafaalagamy/Metrolist/assets/80542861/bfbd3783-17e7-4bf6-961e-88aeced7f0a1)

**Comment by Spaceshiprace** [comment]
the issue is happening when i restore the backup that's all I know

**Comment by ghost** [comment]
@mostafaalagamy do you think this is the same issue? https://github.com/Malopieds/InnerTune/issues/178

**Comment by mostafaalagamy** [comment]
> @mostafaalagamy do you think this is the same issue? https://github.com/Malopieds/InnerTune/issues/178

Yes, it's the same issue. we need to know more about this issue, but I believe it is related to a backup issue.

**Comment by Obandoperea** [comment]
Buen servicio
