### ISSUE TITLE
DOWNLOADING IS NOT WORKING AND ONLINE ARE NOT PLAYING 

### ISSUE THREAD

**Issue by Provo57h** [mostafaalagamy/Metrolist#131]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

DOWNLOADING IS NOT WORKING AND ONLINE ARE NOT PLAYING 

### Expected behavior

DOWNLOADING IS NOT WORKING AND ONLINE ARE NOT PLAYING 

### Actual behavior

DOWNLOADING IS NOT WORKING AND ONLINE ARE NOT PLAYING 

### Screenshots/Screen recordings

DOWNLOADING IS NOT WORKING AND ONLINE ARE NOT PLAYING 

### Logs

DOWNLOADING IS NOT WORKING AND ONLINE ARE NOT PLAYING 

### Metrolist version

10.1.0

### Android version

Android 12

**Comment by mostafaalagamy** [comment]
everything is working perfectly! Are you sure you are using the latest version or the debug version?

**Comment by ImpenetrableNoble** [comment]
@Provo57h Excuse you, but please don't spam the same response whenever you open a new issue about his app please. Thank you.
