### ISSUE TITLE
App translation error

### ISSUE THREAD

**Issue by PiyyStoud** [mostafaalagamy/Metrolist#14]
I have been experimenting with the Dutch language to see if there was a translation problem, and it is no exception, it does not translate the entire interface into that language, this error seems strange to me, you judge.

![pixelcut-export-1720454391119](https://github.com/mostafaalagamy/Metrolist/assets/174969324/9ba04a14-208a-4aba-b7de-4440a9ced61d)

**Comment by mostafaalagamy** [comment]
What version are you using?

**Comment by ghost** [comment]
The version 7.0.0 (Last)

**Comment by mostafaalagamy** [comment]
> The version 7.0.0 (Last)

Yes, the Dutch translation is not yet complete. If you want my help with the translation, you can edit the following string file.

![strings.zip](https://github.com/user-attachments/files/16131980/strings.zip)

**Comment by ghost** [comment]
> > The version 7.0.0 (Last)
> 
> Yes, the Dutch translation is not yet complete. If you want my help with the translation, you can edit the following string file.
> 
> ![strings.zip](https://github.com/user-attachments/files/16131980/strings.zip)

It's ready nooow!!!!

[strings-nl.zip](https://github.com/user-attachments/files/16133228/strings-nl.zip)

**Comment by mostafaalagamy** [comment]
The stable version has been released, you can try it now
