### ISSUE TITLE
10.2.0 playback not working:Unknown Error

### ISSUE THREAD

**Issue by talha5758** [mostafaalagamy/Metrolist#142]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

. 

### Expected behavior

Playback supposed to play normally, having this issue just today right now.

### Actual behavior

doesn't play

### Logs

I don't know how to right now

### Metrolist version

10.2.0

### Android version

14

**Comment by mostafaalagamy** [comment]
Try the latest stable or debug version, but log out for it to work, until I finish identifying and fixing the issue

**Comment by talha5758** [comment]
I'm already on 10.2.0 though...
I don't know how to convert zip file from actions tab to apk

**Comment by mostafaalagamy** [comment]
> I'm already on 10.2.0 though...
> I don't know how to convert zip file from actions tab to apk

You can use MT Manager or any file manager to decompress zip file and open the APK.

**Comment by talha5758** [comment]
my mistake lol, sorry about that, I'm used to downloading just the file because of using rectify11 😅
