### ISSUE TITLE
Offline Metrolist Playback Issue

### ISSUE THREAD

**Issue by ImpenetrableNoble** [mostafaalagamy/Metrolist#160]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open metrolist to the device for offline playback.

2. Turn off Wi-Fi or any other internet connection.

3. Start playing the downloaded offline music.

4. You'll experience an error message from said playback.

### Expected behavior

Metrolist should continue playing the downloaded music without interruption, even with the internet connection disabled.

### Actual behavior

Metrolist unexpectedly stops playing and displays a “network connection lost” error message, despite the device being offline.

### Screenshots/Screen recordings

![Screenshot_20241202_092734](https://github.com/user-attachments/assets/025eb29d-c209-4b05-8e50-51ec23515b68)
![Screenshot_20241202_092723](https://github.com/user-attachments/assets/95d525bb-6367-4b4d-bb03-b4a4e57feb3f)

### Logs

N/A

### Metrolist version

10.3.0

### Android version

Android 12 

### Additional information

This offline playback issue seems to be an recurring problem for me so I would recommend an investigation should be pinned and noted for further additional information I provided.

 * App Bugs: Software glitches or bugs within the music app itself could be causing unexpected behavior, especially when offline.
 * Network Connectivity Issues: Even when Wi-Fi is turned off, there might be residual network connections or background processes trying to access the internet, which could interfere with offline playback.
 * App Permissions: Incorrect app permissions, especially regarding storage access, could prevent the app from accessing downloaded music files.

To further investigate the issue, it would be helpful to gather more specific information, such as:
 * Device Model and Operating System: The type of device and its software version can provide clues about potential compatibility issues.
 * Music App Version: The specific version of the music app being used could be relevant, as certain versions might have known bugs or limitations.
 * Music Format: The format of the downloaded music files (e.g., MP3, AAC, FLAC) could also play a role.
 * Recent Changes: Any recent updates to the device, operating system, or music app might have introduced the issue.

By collecting this information, it might be possible to identify the root cause of the problem and work towards a solution, such as updating the metrolist app, restarting the device, or adjusting app permissions.

**Comment by mostafaalagamy** [comment]
I checked the issue yesterday and didn’t find any errors. I only encountered the problem once, and it was due to recent changes in YouTube API. To resolve this issue, remove the song from your library and likes, search for it again, and then re-add or download it. It should work normally afterward.

**Comment by ImpenetrableNoble** [comment]
@mostafaalagamy Thank you for your previous suggestion, but I want to clarify that the issue I was facing is specifically related to offline music playback. The problem occurs when I play downloaded songs on my device while being offline, and Metrolist unexpectedly stops and displays a 'network connection lost' error message.

Removing and re-adding songs was a temporary solution for me, but I have a substantial music collection, and re-downloading everything would be time-consuming and inconvenient. I have confirmed that the songs are downloaded and accessible offline, but the app still encounters this error.

I'd be happy to provide any additional information or logs that might be helpful for debugging, unfortunately though the app itself doesn't allow me to copy and paste debugging logs here, I think would be great if I can copy and paste logs that metrolist can record to paste it here.

**Comment by mostafaalagamy** [comment]
> @mostafaalagamy Thank you for your previous suggestion, but I want to clarify that the issue I was facing is specifically related to offline music playback. The problem occurs when I play downloaded songs on my device while being offline, and Metrolist unexpectedly stops and displays a 'network connection lost' error message.
> 
> Removing and re-adding songs was a temporary solution for me, but I have a substantial music collection, and re-downloading everything would be time-consuming and inconvenient. I have confirmed that the songs are downloaded and accessible offline, but the app still encounters this error.
> 
> I'd be happy to provide any additional information or logs that might be helpful for debugging, unfortunately though the app itself doesn't allow me to copy and paste debugging logs here, I think would be great if I can copy and paste logs that metrolist can record to paste it here. 
> 
> 

I faced an issue today, and after clearing the cache for the songs, the problem was resolved, and the songs are now working normally. I want you to let me know if this still happens even after the latest update or not. Thank you.
