### ISSUE TITLE
Open Link directly doesn't work

### ISSUE THREAD

**Issue by anxiouslelimo** [mostafaalagamy/Metrolist#162]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open a youtube music link starting with music.youtube.com

### Expected behavior

Metrolist should play the song

### Actual behavior

Metrolist opens to home. That's it.

### Logs

NIL

### Metrolist version

10.3.0

### Android version

Android 14

**Comment by mostafaalagamy** [comment]
The YT Music app takes over the default supported links when you install it, and Metrolist has nothing to do with this. To resolve the issue, you need to uninstall YouTube Music or remove it from the default supported links settings on your device, then enable the "Open Supported Links" option in Metrolist.

**Comment by ghost** [comment]
@mostafaalagamy Tried again. It is working only if metrolist is already opened. Otherwise the app opens to homepage.

**Comment by mostafaalagamy** [comment]
> @mostafaalagamy Tried again. It is working only if metrolist is already opened. Otherwise the app opens to homepage. 

The app must already be open for the song to play directly. I've been trying to solve this issue for a long time, but I have no idea about the root cause of the problem. However, I will try.

**Comment by mostafaalagamy** [comment]
I think the problem has been solved, you can test it now.
