### ISSUE TITLE
Automatic 2-way Syncing

### ISSUE THREAD

**Issue by MoseySlu** [mostafaalagamy/Metrolist#167]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Automatically import Youtube Music library (playlists/albums/artist/history/liked songs) to Metrolist, and automatically sync every time we switch pages (or open app).

### Why do you want this feature?

Would be a huge time saver since we won't have to save everything one by one, manually sync every time we edit a playlist and everything can also be done from Metrolist since both libraries are synced.

**Comment by immortaljam** [comment]
this would be amazing

**Comment by ghost** [comment]
I third this, it would be a super nice addition. It will help me a lot to keep the playlist synced between mobile clients and some desktop client I use.

**Comment by Hikari2w2** [comment]
That'd be fire

**Comment by siggi1984** [comment]
I would also find that great 👍👍👍

**Comment by Chulco** [comment]
I need that for sure... Outertune has this feature and it's awesome.

**Comment by mostafaalagamy** [comment]
Hello everyone, sorry for the delay in responding. I don’t have enough time to be here. Thank you for your understanding.

I have added synchronization now. You can test it, and if you encounter any issues, please let me know.

**Comment by ghost** [comment]
I'll be testing it as soon as the action finishes, thanks a bunch!

**Comment by Hikari2w2** [comment]
> Hello everyone, sorry for the delay in responding. I don’t have enough time to be here. Thank you for your understanding.
> 
> I have added synchronization now. You can test it, and if you encounter any issues, please let me know.

Hi, i hope you're having a good time during Christmas eve, I've just test your latest action out, some playlists are synchronizing correctly, but only a few out of my 199 playlists were imported, (29) likes are correctly synced, history is not syncing however

**Comment by mostafaalagamy** [comment]
I will try to fix the issues as soon as possible. Although I wanted to release the update tomorrow, I will delay it for some time!

**Comment by mostafaalagamy** [comment]
You can now test the bug fix and let me know if there's anything else.

**Comment by immortaljam** [comment]
where do I test it? is it version 10.8.0?

**Comment by Hikari2w2** [comment]
> where do I test it? is it version 10.8.0?

Latest build release , download the signed app. https://github.com/mostafaalagamy/Metrolist/actions/runs/12593087180

**Comment by Hikari2w2** [comment]
> You can now test the bug fix and let me know if there's anything else.

I've test it as well, all my playlists are imported and synchronizing successfully, 

History sync doesn't work though.

You're doing it amazing Sr. Thanks for the quick bug fix.

**Comment by immortaljam** [comment]
> > where do I test it? is it version 10.8.0?
> 
> Latest build release , download the signed app. https://github.com/mostafaalagamy/Metrolist/actions/runs/12593087180

tysm for responding, I got it now.

**Comment by immortaljam** [comment]
I can't add any songs to my playlists

**Comment by Hikari2w2** [comment]
> I can't add any songs to my playlists

Oh, ive just noticed that as well, 😂

**Comment by mostafaalagamy** [comment]
The issue of the playlists list not appearing when adding a song, along with some other problems, has been resolved. However, I haven't added history synchronization yet.

**Comment by immortaljam** [comment]
> The issue of the playlists list not appearing when adding a song, along with some other problems, has been resolved. However, I haven't added history synchronization yet.

tysm for responding, do I need to download a new version of the app for the fix, if so, where can it be found? sorry, I'm kinda bad at these things.

**Comment by mostafaalagamy** [comment]
> > The issue of the playlists list not appearing when adding a song, along with some other problems, has been resolved. However, I haven't added history synchronization yet.
> 
> tysm for responding, do I need to download a new version of the app for the fix, if so, where can it be found? sorry, I'm kinda bad at these things.

You can download the signed version from here:

https://github.com/mostafaalagamy/Metrolist/actions/runs/12611884571

**Comment by Hikari2w2** [comment]
> The issue of the playlists list not appearing when adding a song, along with some other problems, has been resolved. However, I haven't added history synchronization yet.

Hey, thanks so much for your hard work, ive just tested your latest build release, playlists are indeed appearing when adding songs, however, it seems there's a new weird bug when syncing my playlists, now they're all 
![Screenshot_2025-01-05-17-00-38-039_com metrolist music debug-edit](https://github.com/user-attachments/assets/a000038b-648b-4726-8514-64e828ff26f5)
being duplicated, I'm getting like 320 playlists instead of 170.

**Comment by mostafaalagamy** [comment]
> > The issue of the playlists list not appearing when adding a song, along with some other problems, has been resolved. However, I haven't added history synchronization yet.
> 
> Hey, thanks so much for your hard work, ive just tested your latest build release, playlists are indeed appearing when adding songs, however, it seems there's a new weird bug when syncing my playlists, now they're all 
> ![Screenshot_2025-01-05-17-00-38-039_com metrolist music debug-edit](https://github.com/user-attachments/assets/a000038b-648b-4726-8514-64e828ff26f5)
> being duplicated, I'm getting like 320 playlists instead of 170. 

What version did you try?

**Comment by mostafaalagamy** [comment]
> latest build release

What version did you try?

**Comment by Hikari2w2** [comment]
> > latest build release
> 
> What version did you try?

This one Sr. https://github.com/mostafaalagamy/Metrolist/actions/runs/12612913254

**Comment by mostafaalagamy** [comment]
> > > latest build release
> > 
> > What version did you try?
> 
> This one Sr. https://github.com/mostafaalagamy/Metrolist/actions/runs/12612913254

I believe the latest commit resolves this duplication issue, but it won't display some old local playlists that were created before the synchronization release.

**Comment by Fan-Bob** [comment]
I have a question. It seems that it is no longer possible to manually view the playlists in the YouTube Music account and import them?

**Comment by SiriusLightning21** [comment]
> > > > latest build release
> > > 
> > > What version did you try?
> > 
> > This one Sr. https://github.com/mostafaalagamy/Metrolist/actions/runs/12612913254
> 
> I believe the latest commit resolves this duplication issue, but it won't display some old local playlists that were created before the synchronization release.

I´ve been new to Metrolist and have the same issue with duplicate Playlists. I started from scratch login into my youtube music account and the playlists synced fine. After adding a new playlist in youtube music webclient in adds the same new playlist two times to Metrolist. In Youtube music is still only one. If I change the same of the playlist or add a song, I see it also in both playlists.

**Comment by mostafaalagamy** [comment]
> I´ve been new to Metrolist and have the same issue with duplicate Playlists. I started from scratch login into my youtube music account and the playlists synced fine. After adding a new playlist in youtube music webclient in adds the same new playlist two times to Metrolist. In Youtube music is still only one. If I change the same of the playlist or add a song, I see it also in both playlists.

try this version [ 2b416bd](https://github.com/mostafaalagamy/Metrolist/actions/runs/14553201073,)

**Comment by SiriusLightning21** [comment]
> > I´ve been new to Metrolist and have the same issue with duplicate Playlists. I started from scratch login into my youtube music account and the playlists synced fine. After adding a new playlist in youtube music webclient in adds the same new playlist two times to Metrolist. In Youtube music is still only one. If I change the same of the playlist or add a song, I see it also in both playlists.
> 
> try this version [ 2b416bd](https://github.com/mostafaalagamy/Metrolist/actions/runs/14553201073,)

How can I download these files😅 there is no download button.

**Comment by stellessia** [comment]
Any updates on history synchronization? This client is currently the most perfect fork of InnerTune out there, but this one missing feature is a deal breaker for me

**Comment by mostafaalagamy** [comment]
> Any updates on history synchronization? This client is currently the most perfect fork of InnerTune out there, but this one missing feature is a deal breaker for me

This feature already exists!

**Comment by stellessia** [comment]
> > Any updates on history synchronization? This client is currently the most perfect fork of InnerTune out there, but this one missing feature is a deal breaker for me
> 
> This feature already exists!

Hmm, it doesn't seem to work for me on a brand account. I'll create a separate issue tomorrow, if there's no known fix

**Comment by BlazingHotCode** [comment]
I think it does match this one but I have a lot of liked songs on YouTube music, but in metrolist it only shows about half
