### ISSUE TITLE
disabling "auto load more songs" doesn't work

### ISSUE THREAD

**Issue by SlouchingMoh21** [mostafaalagamy/Metrolist#169]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. toggle off "auto load more songs" in the settings
2. start playing the last song from any album or playlist
3. check the current queue, there will be new songs added

### Expected behavior

disabling "auto load more songs" should prevent new songs not on the current album/playlist from being added to the queue 

### Actual behavior

disabling "auto load more songs" adds new songs not on the current album/playlist to the queue when the final song starts playing

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/531da66d-527d-4ee5-9139-afe8a497e144

### Logs

NIL

### Metrolist version

10.5.0

### Android version

Android 11

**Comment by mostafaalagamy** [comment]
As far as I understand the issue, this solution is sufficient: disabling similar content. Try the latest debug version and let me know if there's anything else.

**Comment by SlouchingMoh21** [comment]
that did it! thanks, mate
