### ISSUE TITLE
Unknown error on all songs

### ISSUE THREAD

**Issue by walker-11** [mostafaalagamy/Metrolist#175]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Just play the song

### Expected behavior

.

### Actual behavior

.

### Screenshots/Screen recordings

![Screenshot_20241218-001903_Metrolist](https://github.com/user-attachments/assets/04d87274-3929-498c-9f55-9d7cec23e95c)

### Logs

[18_12-00-44-48_156.log](https://github.com/user-attachments/files/18170343/18_12-00-44-48_156.log)

### Metrolist version

10.7.0

### Android version

15

**Comment by mostafaalagamy** [comment]
I think the problem will return, but in any case, it is working now during login.
