### ISSUE TITLE
sleep timer countdown status isn't displayed 

### ISSUE THREAD

**Issue by ganairm** [mostafaalagamy/Metrolist#181]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

start a sleep timer on any song
-> there's no visual indicator as to how much time there is left

### Expected behavior

there should be an indicator, similar to the original innertune

### Actual behavior

there's absolutely nothing 

### Logs

sorry idk how to get it

### Metrolist version

10.0.8

### Android version

13

**Comment by mostafaalagamy** [comment]
I'm sorry for the delay, the issue has been resolved now.

**Comment by ganairm** [comment]
> I'm sorry for the delay, the issue has been resolved now.

wait really? is there an update?

**Comment by mostafaalagamy** [comment]
> > I'm sorry for the delay, the issue has been resolved now.
> 
> wait really? is there an update?

You can install the latest beta version from the Actions section.

**Comment by ganairm** [comment]
> > > I'm sorry for the delay, the issue has been resolved now.
> > 
> > 
> > wait really? is there an update?
> 
> You can install the latest beta version from the Actions section.

hey uhm thank you for the fix, i really appreciate it but the latest build has a bug. there is no longer an option to add a song into the library, and the songs tab is empty without any way to add songs jn
