### ISSUE TITLE
after clear task,music still playing

### ISSUE THREAD

**Issue by KEVIN970712** [mostafaalagamy/Metrolist#188]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1.open setting,enable stop music on task clear
2.play a song and clear task
3.music still playing

### Expected behavior

music stop playing

### Actual behavior

music keep playing

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/3d49ebef-5b77-44f6-adc0-02f4e92161e6

### Logs

I don't have computer

### Metrolist version

10.8.0

### Android version

Android 13

**Comment by ganairm** [comment]
btw are you using a custom rom?

**Comment by internet-coffee** [comment]
> btw are you using a custom rom?

yes,lineageOS 20(Android 13)
My device is Galaxy A52s 5G

**Comment by mostafaalagamy** [comment]
It works fine on my devices!

**Comment by mostafaalagamy** [comment]
I tried to fix it, you can test it now.
