### ISSUE TITLE
Please Sign in Prompt

### ISSUE THREAD

**Issue by anxiouslelimo** [mostafaalagamy/Metrolist#84]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Random songs showing Please Sign In

### Expected behavior

Song should play

### Actual behavior

Please Sign In prompt appears

### Logs

Nil

### Metrolist version

9.0.0

### Android version

14

### Additional information

When i pause the song after the prompt appears and press play again (sometimes repeat this multiple times), often the prompt dissapears and song starts playing. Ideally a workaround without sign in is best as people who doesn't have a google account or doesn't want google tracking listening habits is best in a privacy standpoint

**Comment by mostafaalagamy** [comment]
I'm looking into this issue and trying to find a way to bypass the login.

**Comment by ghost** [comment]
@mostafaalagamy Some songs fail to download too and few are downloaded after multiple tries. Maybe it's related.
